// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeluqueriaAdmin.Infrastructure.Persistence;

#nullable disable

namespace PeluqueriaAdmin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PeluqueriaDbContext))]
    [Migration("20260719000531_CompleteAdministration")]
    partial class CompleteAdministration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Collaborators.Collaborator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ExitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Collaborators", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Collaborators.DistributionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountMinorUnits");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ParticipantId");

                    b.ToTable("DistributionPayments", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Collaborators.MonthlyClose", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BaseResultMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClosedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollaboratorPercentageBasisPoints")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FundMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GoalMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IncomeMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReopenedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RetainedResultMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Month");

                    b.ToTable("MonthlyCloses", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Collaborators.MonthlyCloseParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountMinorUnits");

                    b.Property<Guid>("CloseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("CloseId", "CollaboratorId")
                        .IsUnique();

                    b.ToTable("MonthlyCloseParticipants", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Finance.FinancialEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountMinorUnits");

                    b.Property<int?>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("FinancialEntries", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CashAmount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CashAmountMinorUnits");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EstimatedCost")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EstimatedCostMinorUnits");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Date");

                    b.ToTable("InventoryMovements", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Inventory.MonthlyRestockPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NeededQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyRestockPlans", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Inventory.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.LocalUse.LocalUsePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountMinorUnits");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("PersonId");

                    b.ToTable("LocalUsePayments", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.LocalUse.LocalUsePerson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LocalUsePeople", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.LocalUse.WeeklyCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountMinorUnits");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "PeriodStart")
                        .IsUnique();

                    b.ToTable("WeeklyCharges", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.LocalUse.WeeklyRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountMinorUnits");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom");

                    b.ToTable("WeeklyRates", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Maintenance.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActualCost")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ActualCostMinorUnits");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EstimatedCost")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EstimatedCostMinorUnits");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceRecords", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Obligations.Obligation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpectedAmount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ExpectedAmountMinorUnits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Recurrence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "DueDate")
                        .IsUnique();

                    b.ToTable("Obligations", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Obligations.ObligationPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountMinorUnits");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObligationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ObligationId");

                    b.ToTable("ObligationPayments", (string)null);
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Settings.GeneralSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollaboratorProfit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CollaboratorProfitBasisPoints");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("CurrencyCode")
                        .IsFixedLength();

                    b.Property<long>("OptionalSuppliesMonthlyBudget")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OptionalSuppliesMonthlyBudgetMinorUnits");

                    b.Property<int>("TotalChairs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WeeklyUsageFee")
                        .HasColumnType("INTEGER")
                        .HasColumnName("WeeklyUsageFeeMinorUnits");

                    b.HasKey("Id");

                    b.ToTable("Settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Settings_CollaboratorProfitBasisPoints", "CollaboratorProfitBasisPoints >= 0 AND CollaboratorProfitBasisPoints <= 10000");

                            t.HasCheckConstraint("CK_Settings_CurrencyCode", "length(CurrencyCode) = 3 AND CurrencyCode GLOB '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_Settings_OptionalSuppliesMonthlyBudgetMinorUnits", "OptionalSuppliesMonthlyBudgetMinorUnits >= 0");

                            t.HasCheckConstraint("CK_Settings_Singleton", "Id = 1");

                            t.HasCheckConstraint("CK_Settings_TotalChairs", "TotalChairs >= 0");

                            t.HasCheckConstraint("CK_Settings_WeeklyUsageFeeMinorUnits", "WeeklyUsageFeeMinorUnits >= 0");
                        });
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Collaborators.DistributionPayment", b =>
                {
                    b.HasOne("PeluqueriaAdmin.Domain.Collaborators.MonthlyCloseParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Collaborators.MonthlyCloseParticipant", b =>
                {
                    b.HasOne("PeluqueriaAdmin.Domain.Collaborators.MonthlyClose", null)
                        .WithMany()
                        .HasForeignKey("CloseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeluqueriaAdmin.Domain.Collaborators.Collaborator", null)
                        .WithMany()
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Inventory.InventoryMovement", b =>
                {
                    b.HasOne("PeluqueriaAdmin.Domain.Inventory.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Inventory.MonthlyRestockPlan", b =>
                {
                    b.HasOne("PeluqueriaAdmin.Domain.Inventory.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.LocalUse.LocalUsePayment", b =>
                {
                    b.HasOne("PeluqueriaAdmin.Domain.LocalUse.LocalUsePerson", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.LocalUse.WeeklyCharge", b =>
                {
                    b.HasOne("PeluqueriaAdmin.Domain.LocalUse.LocalUsePerson", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Obligations.ObligationPayment", b =>
                {
                    b.HasOne("PeluqueriaAdmin.Domain.Obligations.Obligation", null)
                        .WithMany()
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
