// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeluqueriaAdmin.Infrastructure.Persistence;

#nullable disable

namespace PeluqueriaAdmin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PeluqueriaDbContext))]
    partial class PeluqueriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PeluqueriaAdmin.Domain.Settings.GeneralSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollaboratorProfit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CollaboratorProfitBasisPoints");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("CurrencyCode")
                        .IsFixedLength();

                    b.Property<long>("OptionalSuppliesMonthlyBudget")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OptionalSuppliesMonthlyBudgetMinorUnits");

                    b.Property<int>("TotalChairs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WeeklyUsageFee")
                        .HasColumnType("INTEGER")
                        .HasColumnName("WeeklyUsageFeeMinorUnits");

                    b.HasKey("Id");

                    b.ToTable("Settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Settings_CollaboratorProfitBasisPoints", "CollaboratorProfitBasisPoints >= 0 AND CollaboratorProfitBasisPoints <= 10000");

                            t.HasCheckConstraint("CK_Settings_CurrencyCode", "length(CurrencyCode) = 3 AND CurrencyCode GLOB '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_Settings_OptionalSuppliesMonthlyBudgetMinorUnits", "OptionalSuppliesMonthlyBudgetMinorUnits >= 0");

                            t.HasCheckConstraint("CK_Settings_Singleton", "Id = 1");

                            t.HasCheckConstraint("CK_Settings_TotalChairs", "TotalChairs >= 0");

                            t.HasCheckConstraint("CK_Settings_WeeklyUsageFeeMinorUnits", "WeeklyUsageFeeMinorUnits >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
